apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: tmax
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
