
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-system-admin
  namespace: console-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
  
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-gateway-cluster-role-binding-console
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: api-gateway-system
roleRef:
  kind: ClusterRole
  name: console-system-admin
  apiGroup: rbac.authorization.k8s.io
