apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: openid-connect
config:
  audience_claim:
    - aud
  hide_credentials: true
  auth_methods:
    - client_credentials
    - authorization_code
    - bearer
    - kong_oauth2
    - refresh_token
  authenticated_groups_claim:
    - clientId
  client_id:
    - ck-integration-hypercloud5
  client_secret:
    - c40ed16e-b513-431f-b41c-98fa6fd7ea27
  issuer: https://hyperauth.org/auth/realms/tmax
  upstream_headers_claims:
    - clientId
  upstream_headers_names:
    - my-client-id
  upstream_access_token_header: " "
  verify_claims: false
plugin: openid-connect
