# kubectl create secret \
# generic app-admin-jwt -n console-system \
# --from-literal=kongCredType=jwt  \
# --from-literal=key="https://hyperauth.org/auth/realms/tmax" \
# --from-literal=algorithm=RS256 \
# --from-literal=rsa_public_key="-----BEGIN PUBLIC KEY-----
# MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkZcgdR+ufcL+5hdQzdOtIaA3Bzp1Wf2eQFYh5Yy64pMrXUD+5TEyDRfNp96sUb7ay+b15vJmTmePMtPn+pV5TrQHXT1YtLgvhLmJtO/tHreqC1/zqnchBdtVBPkfhvLYRiqBKKpR1bNB3UUg6A7LWh/NGj1FX7EGYIqlKX6lb2k6QbWQRNOiQFtygV9WfTo9Oq5u518aYe8MnJECQC7z14MRgEihDxlUkEhSPiTIwtQeYlzG9mnIz/v+VZ3gO8Tq3ap7jrGKbwrSZPq7IeQR93BislXlFGAM2ujqkF8rRqywkKf3r84L5oG94/8xQuVYZSkvC586g72kD7btt3qoGwIDAQAB
# -----END PUBLIC KEY-----"

apiVersion: v1
kind: Secret
metadata:
  name: app-admin-jwt
  namespace: console-system
type: Opaque
stringData:
  kongCredType: jwt
  key: https://hyperauth.org/auth/realms/tmax
  algorithm: RS256
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkZcgdR+ufcL+5hdQzdOtIaA3Bzp1Wf2eQFYh5Yy64pMrXUD+5TEyDRfNp96sUb7ay+b15vJmTmePMtPn+pV5TrQHXT1YtLgvhLmJtO/tHreqC1/zqnchBdtVBPkfhvLYRiqBKKpR1bNB3UUg6A7LWh/NGj1FX7EGYIqlKX6lb2k6QbWQRNOiQFtygV9WfTo9Oq5u518aYe8MnJECQC7z14MRgEihDxlUkEhSPiTIwtQeYlzG9mnIz/v+VZ3gO8Tq3ap7jrGKbwrSZPq7IeQR93BislXlFGAM2ujqkF8rRqywkKf3r84L5oG94/8xQuVYZSkvC586g72kD7btt3qoGwIDAQAB
    -----END PUBLIC KEY-----

---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: admin
  namespace: console-system
  annotations:
    kubernetes.io/ingress.class: kong
username: apiUser
credentials:
  - app-admin-jwt

---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: app-jwt
  namespace: console-system
plugin: jwt

---
# kubectl patch ingress console -n console-system -p '{"metadata":{"annotations":{"konghq.com/plugins":"app-jwt"}}}'
