apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: api-gateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
      hypercloud: ui
  template:
    metadata:
      labels:
        app: console
        hypercloud: ui
      name: hypercloud-ui
    spec:
      containers:
        - command:
            - /opt/bridge/bin/console
            - server
            - --public-dir=/opt/bridge/static
            - --dynamic-file=/opt/bridge/configs/dynamic-config.yaml
            - --listen=https://0.0.0.0:443
            - --base-address=https://0.0.0.0:443
            - --redirect-port=80
            - --tls-cert-file=/var/https-cert/tls.crt
            - --tls-key-file=/var/https-cert/tls.key
            - --keycloak-realm=tmax
            - --keycloak-auth-url=https://hyperauth.org/auth
            - --keycloak-client-id=ck-integration-hypercloud5
            - --mc-mode=false
            - --grafana-endpoint=http://grafana.monitoring.svc:3000/api/grafana/
            # - --kiali-endpoint=https://@@KIALI@@/api/kiali
            # - --kibana-endpoint=http://@@KIBANA@@/api/kibana/
            # - --kubeflow-endpoint=http://@@KUBEFLOW@@/api/kubeflow/
            # - --managed-gitlab-url=@@GITLAB@@
          image: tmaxcloudck/hypercloud-console:v21.0.3.1
          imagePullPolicy: Always
          name: console
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/https-cert
              name: https-cert
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /etc/timezone
              name: timezone
              readOnly: true
            - mountPath: /opt/bridge/configs
              name: dynamic-config
        - command:
            - /manager
          args:
            - --pwd=/var/tmp/configs/
          image: tmaxcloudck/console-operator:5.1.0.1
          name: manager
          volumeMounts:
            - mountPath: /var/tmp/configs
              name: dynamic-config
      serviceAccount: api-gateway
      volumes:
        - name: https-cert
          secret:
            defaultMode: 288
            secretName: api-gateway-server-tls
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
        - hostPath:
            path: /etc/timezone
            type: ""
          name: timezone
        - emptyDir:
            medium: "Memory"
          name: dynamic-config
